### ISSUE TITLE
I DELETED YOU SHITTY TOKEN GRABBER

### ISSUE THREAD

**Issue by xcarx** [Methods101/Mqxl-Selfbot#1]
ez i deleted you token grabber

**Comment by IlluminatiFish** [comment]
nice work

**Comment by Methods101** [comment]
its not a token grabber only 1 command uses webhooks u can change it if you want to its for checking Roblox cookies idc what you think just mess around with it its not my problem if something happens to your account because its checked before being used

**Comment by GAGOU78** [comment]
line 343 on you shitty exeter skid idiot

**Comment by IlluminatiFish** [comment]
> its not a token grabber only 1 command uses webhooks u can change it if you want to its for checking Roblox cookies idc what you think just mess around with it its not my problem if something happens to your account because its checked before being used

lmfao you're funny https://github.com/Methods101/Mqxl-Selfbot/blob/054e6b20f5365ae4bd881ac6f252a29733fe8d47/main.py#L347
